FROM node:18-alpine

# Create a app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Run npm install
RUN npm install

# Bundle app source
COPY . .

EXPOSE 1313

CMD [ "npm", "start" ]